CREATE SCHEMA BD_PHP;
USE BD_PHP;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE IF NOT EXISTS `crudphp` (
  `CodigoDoUsuario` int(11) PRIMARY KEY NOT NULL auto_increment,
  `nome` varchar(13) DEFAULT NULL,
  `usuario` varchar(15) DEFAULT NULL,
  `senha` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `crudphp` (`CodigoDoUsuario`, `nome`, `usuario`, `senha`) VALUES
(2, 'Nome1', 'teste1', '123456'),
(3, 'Nome2', 'teste2', '654321'),
(4, 'Nome3', 'teste3', '242424'),
(5, 'Nome4', 'teste4', '987654321');


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
